// Generated by scripts/build-atlas.py from atlas.png; do not edit.
.pragma library

var cols = 16
var rows = 24
var count = 376
var rainCount = 177
var blocks = {"katakana": [[0, 45], [64, 55]], "text": [[177, 42]], "greek": [[219, 23]], "runes": [[242, 24]], "braille": [[266, 34]], "box": [[300, 28]], "hieroglyphs": [[328, 24]], "alchemy": [[352, 24]]}
var text = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789:.!?-'"
