#!/usr/bin/env python3
"""Rebuild the glyph atlas using Noto Sans CJK JP (SIL OFL 1.1).

The first 64 glyphs are the original set (half-width katakana, digits and a
few symbols); the rest extend it in the same style. Glyphs are stretched
vertically so katakana fill the cell height, and only narrow glyphs are used
so columns stay single file.
Writes atlas.png, atlas.json and atlas.js; RainLayer.qml and
screensaver/Screensaver.qml read the grid size from atlas.js.
"""
import argparse
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageOps

CELL = 128
COLS = 16
SIZE = 112
MARGIN = 6  # px kept free above and below a katakana glyph
MAX_ADVANCE = 0.72  # ems; keeps out full-width and wide glyphs (M, W)

ORIGINAL = 'ｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝ0123456789:.=*+-<>|'

# (characters, mirrored)
EXTRA = [
    ('ｦｧｨｩｪｫｬｭｮｯｰ', False),
    ('ｦｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝ', True),
    ('0123456789', True),
    ('ABCDEFGHIJKLMNOPQRSTUVWXYZ', False),
    ('BCDEFGJKLNPQRSZ', True),
    ('!"#$%&\'(),/;?@[\\]^_{}~¦¥§×÷±√∞≠≤≥ΣΔΠΦΨΩλπ', False),
]


# Glyph sets, appended after the rain's own glyphs as contiguous blocks (so a
# set is one or two index ranges). (name, characters, font). TEXT is also the
# alphabet for messages and the clock.
TEXT = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789:.!?-'"
BLOCKS = [
    ('text', TEXT, 'cjk'),
    ('greek', 'αβγδεζηθικλμνξπρστυφχψω', 'cjk'),
    ('runes', 'ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛇᛈᛉᛊᛏᛒᛖᛗᛚᛜᛞᛟ', 'runic'),
    ('braille', ''.join(chr(0x2800 + v) for v in (
        1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 35, 39, 45, 51,
        57, 63, 71, 85, 99, 107, 119, 127, 150, 173, 199, 219, 238, 255)), 'symbols:fit:⣿'),
    ('box', '│┃║┆┊╎╏┼╋╬├┤┬┴┌┐└┘╔╗╚╝▌▐█▓▒░', 'cjk:fill:┼'),
    ('hieroglyphs', ''.join(chr(c) for c in (
        0x13080, 0x13153, 0x131CB, 0x1309D, 0x130C0, 0x13171, 0x131BC, 0x13216, 0x13283, 0x132AA,
        0x132F9, 0x13379, 0x133CF, 0x13000, 0x13050, 0x1306B, 0x130B7, 0x130F7, 0x1310F, 0x13191,
        0x131E0, 0x13254, 0x13399, 0x1340D)), 'hiero:each'),
    ('alchemy', ''.join(chr(c) for c in (
        0x1F701, 0x1F702, 0x1F703, 0x1F704, 0x1F70D, 0x1F714, 0x1F71A, 0x1F71B, 0x1F720, 0x1F729,
        0x1F72A, 0x1F739, 0x1F746, 0x1F74A, 0x1F750, 0x1F753, 0x1F755, 0x1F75E, 0x1F76A, 0x1F771,
        0x1F736, 0x1F73F, 0x1F744, 0x1F70A)), 'symbols1:each'),
]
FONTS = {
    'cjk': '/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc',
    'runic': '/usr/share/fonts/noto/NotoSansRunic-Regular.ttf',
    'symbols': '/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf',
    'symbols1': '/usr/share/fonts/noto/NotoSansSymbols-Regular.ttf',
    'hiero': '/usr/share/fonts/noto/NotoSansEgyptianHieroglyphs-Regular.ttf',
}


def atlas_js(meta):
    return ('// Generated by scripts/build-atlas.py from atlas.png; do not edit.\n'
            '.pragma library\n\n'
            f"var cols = {meta['cols']}\n"
            f"var rows = {meta['rows']}\n"
            f"var count = {meta['count']}\n"
            f"var rainCount = {meta['rainCount']}\n"
            f"var blocks = {json.dumps(meta['blocks'])}\n"
            f"var text = {json.dumps(TEXT)}\n")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--font', default='/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc')
    a = p.parse_args()
    font = ImageFont.truetype(a.font, SIZE, index=0)

    def layer(ch, f=font):
        g = Image.new('RGBA', (CELL, CELL * 2), (255, 255, 255, 0))
        ImageDraw.Draw(g).text((CELL // 2, CELL), ch, font=f, anchor='mm', fill='white')
        return g

    # Stretch every glyph by the same factor, chosen so the katakana ink band
    # fills the cell height, and centre that band in the cell. Width is kept.
    _, top, _, bottom = layer('ｱ').getbbox()
    stretch = (CELL - 2 * MARGIN) / (bottom - top)
    tall = round(CELL * 2 * stretch)
    crop_top = round((top + bottom) / 2 * stretch - CELL / 2)

    def draw(ch, mirror, f=font):
        g = layer(ch, f).resize((CELL, tall), Image.LANCZOS)
        g = g.crop((0, crop_top, CELL, crop_top + CELL))
        return ImageOps.mirror(g) if mirror else g

    def draw_scaled(ch, f, fill, ref):
        # Scale by a reference glyph's ink box (the full braille cell or the
        # box-drawing cross), the same for the whole block, so dots and lines
        # keep their places: `fill` stretches that box over the glyph area
        # (box lines join up between rows), otherwise it keeps its shape.
        def big(c):
            g = Image.new('RGBA', (CELL * 2, CELL * 2), (255, 255, 255, 0))
            ImageDraw.Draw(g).text((CELL, CELL), c, font=f, anchor='mm', fill='white')
            return g
        box = big(ref).getchannel('A').getbbox()
        ink = big(ch).crop(box)
        w, h = CELL * 0.78, CELL
        if not fill:
            k = min(w / ink.width, (CELL - 2 * MARGIN) / ink.height)
            w, h = ink.width * k, ink.height * k
        ink = ink.resize((max(1, round(w)), max(1, round(h))), Image.LANCZOS)
        out = Image.new('RGBA', (CELL, CELL), (255, 255, 255, 0))
        out.alpha_composite(ink, ((CELL - ink.width) // 2, (CELL - ink.height) // 2))
        return out

    def draw_fit(ch, f):
        # Set glyphs keep every character (no width filter): wide ones are
        # squeezed to the width a katakana glyph uses.
        g = draw(ch, False, f)
        box = g.getchannel('A').getbbox()
        if box is None:
            return g
        limit = CELL * 0.78
        if box[2] - box[0] > limit:
            ink = g.crop((box[0], 0, box[2], CELL)).resize((round(limit), CELL), Image.LANCZOS)
            g = Image.new('RGBA', (CELL, CELL), (255, 255, 255, 0))
            g.alpha_composite(ink, (round((CELL - limit) / 2), 0))
        return g

    # Skip glyphs that are wide, invisible inside the cell, or identical to
    # one already in (symmetric glyphs mirror onto themselves).
    layers = [draw(ch, False) for ch in ORIGINAL]

    def shape(g):
        # Coarse outline, so mirrored symmetric glyphs that differ only in
        # antialiasing still count as duplicates.
        return g.getchannel('A').resize((16, 16), Image.BOX).point(lambda v: 1 if v > 96 else 0).tobytes()

    def duplicate(a):
        return any(sum(x != y for x, y in zip(a, b)) <= 6 for b in seen)

    seen = [shape(g) for g in layers]
    group_starts = []
    for chars, mirror in EXTRA:
        group_starts.append(len(layers))
        for ch in chars:
            if font.getlength(ch) / SIZE > MAX_ADVANCE:
                continue
            g = draw(ch, mirror)
            key = shape(g)
            if duplicate(key) or g.getchannel('A').getbbox() is None:
                continue
            seen.append(key)
            layers.append(g)

    rain_count = len(layers)
    # Katakana only: the original 45, then the extra and mirrored katakana
    # (EXTRA groups 0 and 1).
    blocks = {'katakana': [[0, 45], [group_starts[0], group_starts[2] - group_starts[0]]]}
    for name, chars, spec in BLOCKS:
        fkey, how, ref = (spec.split(':') + ['', ''])[:3]
        f = ImageFont.truetype(FONTS[fkey], SIZE, index=0)
        blocks[name] = [[len(layers), len(chars)]]
        for ch in chars:
            if how == 'each':
                layers.append(draw_scaled(ch, f, False, ch))
            else:
                layers.append(draw_scaled(ch, f, how == 'fill', ref) if how else draw_fit(ch, f))

    rows = -(-len(layers) // COLS)
    im = Image.new('RGBA', (COLS * CELL, rows * CELL), (255, 255, 255, 0))
    for i, g in enumerate(layers):
        im.alpha_composite(g, ((i % COLS) * CELL, (i // COLS) * CELL))

    root = Path(__file__).resolve().parents[1]
    im.save(root / 'atlas.png', optimize=True)
    meta = {'cols': COLS, 'rows': rows, 'cell': CELL, 'count': len(layers),
            'rainCount': rain_count, 'blocks': blocks,
            'width': im.width, 'height': im.height}
    (root / 'atlas.json').write_text(json.dumps(meta) + '\n')
    (root / 'atlas.js').write_text(atlas_js(meta))
    print(json.dumps(meta))


if __name__ == '__main__':
    main()
